package souradippatra.Spring_Security_Identity_Server.mapper;

import souradippatra.Spring_Security_Identity_Server.dto.UserAccountDTO;
import souradippatra.Spring_Security_Identity_Server.model.UserAccount;

public class UserAccountMapper {

    // Entity → DTO
    public static UserAccountDTO toDTO(UserAccount entity) {
        if (entity == null) return null;
        return new UserAccountDTO(entity.getId(), entity.getUsername(), entity.getRole());
    }

    // DTO → Entity
    public static UserAccount toEntity(UserAccountDTO dto) {
        if (dto == null) return null;
        UserAccount entity = new UserAccount();
        entity.setId(dto.getId()); // optional; usually autogenerated
        entity.setUsername(dto.getUsername());
        entity.setRole(dto.getRole());
        return entity;
    }
}
